x=lambda x:x.upper()
print(x("python"))
a=lambda x:x.casefold()
print(a("PYTHON"))
b=lambda x:x.lower()
print(b('pyhon'))
c=lambda x:x.center(100)
print(c("python"))
d=lambda x:x.index('t')
print(d('python'))
c=lambda x:x.removeprefix('p')
print(c("python"))
x=lambda x:x.removesuffix('n')
print(x('python'))
x=lambda x:x.replace('s','r')
print(x("hello supriya"))
x=lambda x:x.split(' ')
print(x("python"))
x=lambda x:x.count("s")
print(x("sannysanjjusand"))
x=lambda x:x.swapcase()
print(x("python"))
